title: Rest Is Good
author: GitHub User
email: your-email@domain.com
description: This is description
show_excerpts: true # set to true to show excerpts on the homepage
baseurl:

remote_theme: thelehhman/texture
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass

permalink: /posts/:title/
texture:
  title: Rest
  tagline: is good.
  date_format: "%b %-d, %Y"
  style: blue
  showNav: true
  showPicker: false

  # generate social links in footer
  social_links:
    github:  Dorika0203
 

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
# theme: texture

plugins:
  - jekyll-seo-tag
#  - jekyll-feed 
